server:
  port: 8888

spring:
  application:
    name: config-service
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
  profiles:
    active: native
  cloud:
    config:
      server:
#        native:
#          search-locations: file:///C:\Temp\CONFIG_SERVER_NATIVE_REPO
        git:
          uri: https://github.com/brunosong/spring-cloud-config_yml

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh

