server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/brunosong/spring-cloud-config_yml
          #uri: file://C:\Temp\CONFIG_SERVER_GIT  #?? ????? ???? ?? ??????? ????.
#          username:
#          password:


